# Generated by Django 4.2.6 on 2024-06-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.IntegerField()),
                ('genero', models.CharField(choices=[('D', 'Masculino'), ('I', 'Femenino'), ('O', 'Otro')], max_length=100)),
                ('estado', models.CharField(choices=[('D', 'Dependiente'), ('I', 'Independiente')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('sueldo', models.FloatField()),
                ('photo', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='CalculosSeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pensiones', models.FloatField()),
                ('salud', models.FloatField()),
                ('base', models.FloatField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='nomina.nomina')),
            ],
        ),
    ]
