# Generated by Django 4.2.6 on 2024-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_alter_nomina_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculosseguridadsocial',
            name='arl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculosseguridadsocial',
            name='caja_compensacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nivel_riesgo',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomina',
            name='genero',
            field=models.CharField(choices=[('D', 'Masculino'), ('I', 'Femenino'), ('O', 'Otro')], max_length=100),
        ),
    ]
