# Generated by Django 5.0.6 on 2024-06-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_alter_nomina_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='horas_extras',
            field=models.IntegerField(default=0),
        ),
    ]
