# Generated by Django 5.0.6 on 2024-06-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_nomina_horas_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='horas_extras',
        ),
        migrations.AddField(
            model_name='calculosseguridadsocial',
            name='auxilio_transporte',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculosseguridadsocial',
            name='prima',
            field=models.FloatField(default=0),
        ),
    ]
