# Generated by Django 5.0.6 on 2024-06-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_remove_nomina_horas_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='horas_extras',
            field=models.IntegerField(default=0),
        ),
    ]
