# Generated by Django 5.0.6 on 2024-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_nomina_horas_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='horas_extras',
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extras_diurnas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extras_diurnas_dominicales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extras_nocturnas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='estado',
            field=models.CharField(choices=[('D', 'Dependiente'), ('I', 'Independiente')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
