# Generated by Django 4.2.6 on 2024-06-24 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_remove_nomina_horas_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='fecha_contratacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
