# Generated by Django 4.2.6 on 2024-06-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_nomina_fecha_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='tipo_contrato',
            field=models.CharField(choices=[('TF', 'Termino Fijo'), ('TI', 'Termino Indefinido'), ('P', 'Prácticas')], default='TF', max_length=2),
        ),
    ]
