# Generated by Django 4.2.6 on 2024-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0010_nomina_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='tipo_contrato',
            field=models.CharField(choices=[('TF', 'Término Fijo'), ('TI', 'Término Indefinido'), ('P', 'Prácticas')], max_length=2),
        ),
    ]
