# Generated by Django 4.2.6 on 2024-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_email_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(default='', upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
