# Generated by Django 4.2.6 on 2024-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.IntegerField()),
                ('cargo', models.IntegerField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.IntegerField()),
                ('genero', models.IntegerField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], max_length=100)),
                ('photo', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
