# Generated by Django 4.2.6 on 2024-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.IntegerField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de cuidadania'), ('TI.', 'Targeta de identificación')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
